apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ASP.NET Core service created from the example .NET template
spec:
  type: service
  owner: user:guest
  lifecycle: experimental